#!/bin/bash


open -n -a Google\ Chrome
sleep 1s 
open -a Google\ Chrome https://www.brainville.com/Market/RequisitionSearchResult
open -a Google\ Chrome https://supplier.eworkgroup.com/app/job-requests?page=0&size=20&sortConfig=%5B%7B%22sortBy%22%3A%22firstDayOfApplications%22%2C%22order%22%3A%22DESC%22%7D%5D&filtersConfig=%7B%22languages%22%3A%5B%5D%2C%22skills%22%3A%5B%5D%2C%22skillRoleCategories%22%3A%5B%5D%2C%22location%22%3A%7B%22city%22%3Anull%2C%22country%22%3A%22Sweden%22%2C%22name%22%3A%22Stockholm%20County%2C%20Sweden%22%2C%22locationId%22%3A%22NT_ggmqOD.kp-CmBdZgCiCBaC%22%7D%7D
open -a Google\ Chrome https://portal.afry.com/en/AvailableAssignments
open -a Google\ Chrome https://keyman.se/uppdrag/
open -a Google\ Chrome https://upgraded.se/konsultuppdrag/
open -a Google\ Chrome https://www.profinder.se/uppdrag-19993191
open -a Google\ Chrome https://www.nikita.se/lediga-uppdrag/
open -a Google\ Chrome https://www.nikita.se/ramavtal/
open -a Google\ Chrome https://consultnord.se/jobs
open -a Google\ Chrome http://www.emaco.se/assignments
open -a Google\ Chrome https://www.gabert-partners.se/lediga-uppdrag
open -a Google\ Chrome https://www.techrelations.se/konsultuppdrag
open -a Google\ Chrome https://www.safemind.se/konsulter/
open -a Google\ Chrome https://onsiter.com/se/uppdrag
open -a Google\ Chrome https://www.swcg.com/jobs
open -a Google\ Chrome https://levigo.se/
open -a Google\ Chrome https://regent.se/uppdrag/
open -a Google\ Chrome https://www.tingent.se/jobs.html
open -a Google\ Chrome http://paventia.se/uppdrag/
open -a Google\ Chrome http://www.atiendo.se/aktuella-uppdrag/
open -a Google\ Chrome https://partnernetworkportal.azurewebsites.net/
open -a Google\ Chrome https://enmanskonsulterna.se/
open -a Google\ Chrome https://jobb.bravura.se/lediga-jobb/?jobtypes=696101
open -a Google\ Chrome https://jobb.senterprise.se/departments/konsultuppdrag
open -a Google\ Chrome https://www.7n.com/job-offers
open -a Google\ Chrome "https://account.asociety.se/#/assignments"
open -a Google\ Chrome https://www.konsulter.net/freelance-jobs/
open -a Google\ Chrome https://www.konsultfabriken.se/all-assignments.php
open -a Google\ Chrome https://www.meone.se/jobb/
open -a Google\ Chrome https://www.wiseit.se/lediga-tjanster/?sleek_filter_tax_sleekteamtailor_job_category%5B%5D=&sleek_filter_tax_sleekteamtailor_job_category%5B%5D=&sleek_filter_tax_sleekteamtailor_job_location=&sleek_filter_tax_sleekteamtailor_job_type=803&sleek_filter_search=
open -a Google\ Chrome https://www.jobserve.com/se/en/JobSearch.aspx?shid=8B1872B9B38854BD782C
open -a Google\ Chrome https://www.konsultuppdrag.com/jobs-3/
open -a Google\ Chrome https://www.sigmaindustryeastnorth.se/partnersidan/
open -a Google\ Chrome https://datakonsulter.info/WiseDki/StartController#assignments
open -a Google\ Chrome https://resursbrist.se/aktuella-uppdrag/
open -a Google\ Chrome https://kantur.se/leads/
open -a Google\ Chrome https://www.biolit.se/konsultuppdrag/