# För att snabbt koppla upp 
# till en samling konsultförmedlare som har uppdragserbjudanden.
# Om du vill lägga till är det bara följa formatet nedan.

start chrome https://www.brainville.com/PublicPage/Login 
    start chrome https://supplier.eworkgroup.com/app/job-requests?page=0&size=20&sortConfig=%5B%7B%22sortBy%22%3A%22firstDayOfApplications%22%2C%22order%22%3A%22DESC%22%7D%5D&filtersConfig=%7B%22languages%22%3A%5B%5D%2C%22skills%22%3A%5B%5D%2C%22skillRoleCategories%22%3A%5B%5D%2C%22location%22%3A%7B%22city%22%3Anull%2C%22country%22%3A%22Sweden%22%2C%22name%22%3A%22Stockholm%20County%2C%20Sweden%22%2C%22locationId%22%3A%22NT_ggmqOD.kp-CmBdZgCiCBaC%22%7D%7D
    start chrome https://portal.afry.com/en/AvailableAssignments
    start chrome https://keyman.se/uppdrag/
    start chrome https://upgraded.se/rekrytering
    start chrome https://www.profinder.se/uppdrag-19993191
    start chrome https://www.nikita.se/lediga-uppdrag/
    start chrome https://consultnord.se/jobs
    start chrome http://www.emaco.se/assignments
    start chrome https://www.gabert-partners.se/lediga-uppdrag
    start chrome https://www.techrelations.se/konsultuppdrag
    start chrome https://www.safemind.se/lediga-jobb-tjanster/?tmp=1
    start chrome https://onsiter.com/se/uppdrag
    start chrome https://www.swcg.com/jobs
    start chrome https://levigo.se/
    start chrome https://regent.se/uppdrag/
    start chrome https://www.tingent.se/jobs.html
    start chrome https://jobb.mscsolutions.se/
    start chrome http://paventia.se/uppdrag/?search_keywords=design
    start chrome http://www.atiendo.se/aktuella-uppdrag/
    start chrome https://app.brainping.com/latest-contracts/
    start chrome https://combitech.se/lediga-jobb/
    start chrome https://enmanskonsulterna.se/hitta-uppdrag
    start chrome https://jobb.bravura.se/lediga-jobb/?categories=558201
    start chrome https://jobb.senterprise.se/jobs
    start chrome https://jobs.academicwork.se/?L=Stockholms
    start chrome https://se.indeed.com/jobb?q=Konsultuppdrag+utvecklare&l=
    start chrome https://thehub.io/jobs?positionTypes=5b8e46b3853f039706b6ea75
    start chrome https://www.7n.com/job-offers
    start chrome "https://account.asociety.se/#/assignments"
    start chrome https://www.jobbusters.se/lediga-jobb/
    start chrome https://www.kimm.se/lediga-jobb/?filter_pnty_q=
    start chrome https://www.konsulter.net/freelance-jobs/
    start chrome https://www.konsultfabriken.se/all-assignments.php
    start chrome https://www.meone.se/jobb/
    start chrome https://www.piscer.se/konsultuppdrag
    start chrome https://www.tng.se/lediga-jobb?ort=Stockholm
    start chrome https://www.uptrail.com/sv/it-tech
    start chrome https://www.wise.se/lediga-jobb/?filter_pnty_q=
    start chrome https://www.wiseit.se/lediga-tjanster/?filter_pnty_job_tag=
    start chrome https://www.northab.com/jobs
    start chrome https://www.jobserve.com/se/en/JobSearch.aspx?shid=AA56B564271141ED47
    start chrome https://www.dreamwork.se/engineering/lediga-tjanster/?locations=stockholms-lan&assign=engineering
    start chrome https://www.adecco.se/lediga-jobb/inom-stockholms-l%C3%A4n-yrke-ingenj%C3%B6r-teknik/
    start chrome https://www.konsultuppdrag.com/jobs-3/
    start chrome https://www.sigmaindustryeastnorth.se/lediga-jobb/
    start chrome https://datakonsulter.info/WiseDki/StartController#assignments
    start chrome https://resursbrist.se/aktuella-uppdrag/
    start chrome https://kantur.se/leads/